name: Release

# Trigger the workflow on push tags like "v*.*.*" (version tags)
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build release binary
        run: cargo build --release

      - name: Create release archive
        run: |
          mkdir -p release
          cp target/release/spaced release/spaced
          cp target/release/space-cli release/space-cli
          tar -czvf release.tar.gz release/

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: test-release
          release_name: test-release-name
          body: |
            Automated release of version ${{ github.ref }}.
          draft: false  # Set to true if you want to create a draft release
          prerelease: false  # Set to true if this is a pre-release
          files: release.tar.gz  # Path to the files you want to upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token for authentication

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.tar.gz  # Ensure this matches your archive
          asset_name: release.tar.gz  # Update to the name of your archive
          asset_content_type: application/gzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Add the token here too

